import {Metadata} from 'next';
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar"
import "./globals.css";
import MapBox from '@/components/map/map'
import App from './page'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="root-body">
          
          <section className='aaa'>
            <div className="header-container">
              <Header />
            </div>
            <App/>
          </section>
      </body>
    </html>
  );
}